In [1]:
from sklearn import preprocessing
import matplotlib.pyplot as plt; plt.rcdefaults()
import numpy as np
import matplotlib.pyplot as plt
 

In [2]:
labels=["NO","YES"]
import pandas as pd
data = pd.read_csv('diabetic1.csv',converters={49:lambda s: labels.index(s)})
print(data.shape)
print(data.columns)

(65499, 50)
Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')


In [3]:
data1 = data
data1 = data1.drop(columns=['admission_type_id','discharge_disposition_id','admission_source_id','weight','payer_code','medical_specialty','acetohexamide','examide','citoglipton','glimepiride-pioglitazone', 'metformin-rosiglitazone','max_glu_serum','glyburide-metformin','glipizide-metformin','metformin-pioglitazone','encounter_id', 'patient_nbr'])

In [4]:
data1 = data1.replace("?",np.nan) 
data1 = data1.dropna() 
data1.shape

(62945, 33)

In [5]:
data1.describe()

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
count      62945.000000        62945.000000    62945.000000     62945.000000   
mean           4.558615           42.780094        1.358345        15.740186   
std            3.068419           19.123392        1.682986         8.185239   
min            1.000000            1.000000        0.000000         1.000000   
25%            2.000000           31.000000        0.000000        10.000000   
50%            4.000000           44.000000        1.000000        14.000000   
75%            6.000000           56.000000        2.000000        20.000000   
max           14.000000          129.000000        6.000000        81.000000   

       number_outpatient  number_emergency  number_inpatient  \
count       62945.000000      62945.000000      62945.000000   
mean            0.281118          0.149877          0.616506   
std             1.034566          0.666082          1.228668   
min             0.000000          0.000000          0.000000   
25%             0.000000          0.000000          0.000000   
50%             0.000000          0.000000          0.000000   
75%             0.000000          0.000000          1.000000   
max            42.000000         42.000000         21.000000   

       number_diagnoses    readmitted  
count      62945.000000  62945.000000  
mean           7.208309      0.478878  
std            1.892782      0.499558  
min            3.000000      0.000000  
25%            6.000000      0.000000  
50%            8.000000      0.000000  
75%            9.000000      1.000000  
max            9.000000      1.000000

data1 = data1.replace("?",np.nan)
data1 = data1.dropna()
data1.shape

<h2> One Hot Encoding </h2>

In [6]:
le = preprocessing.LabelEncoder()
le.fit(['No' ,'Steady', 'Down' ,'Up'])
data1['metformin']=le.transform(data1['metformin']) 
le = preprocessing.LabelEncoder()
le.fit(['No' ,'Steady', 'Down' ,'Up'])
data1['repaglinide']=le.transform(data1['repaglinide']) 
le = preprocessing.LabelEncoder()
le.fit(['No' ,'Steady', 'Down' ,'Up'])
data1['nateglinide']=le.transform(data1['nateglinide']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['chlorpropamide']=le.transform(data1['chlorpropamide']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['glimepiride']=le.transform(data1['glimepiride']) 
le.fit(['No','Steady','Down','Up'])
data1['glipizide']=le.transform(data1['glipizide']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['glyburide']=le.transform(data1['glyburide'])
le = preprocessing.LabelEncoder()
le.fit(['No','Steady'])
data1['tolbutamide']=le.transform(data1['tolbutamide']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['pioglitazone']=le.transform(data1['pioglitazone']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['rosiglitazone']=le.transform(data1['rosiglitazone']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['acarbose']=le.transform(data1['acarbose']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['miglitol']=le.transform(data1['miglitol']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady'])
data1['troglitazone']=le.transform(data1['troglitazone']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Up'])
data1['tolazamide']=le.transform(data1['tolazamide']) 
le = preprocessing.LabelEncoder()
le.fit(['Caucasian', 'AfricanAmerican', 'Hispanic', 'Others', 'Asian','Other'])
data1['race']=le.transform(data1['race']) 
le = preprocessing.LabelEncoder()
le.fit(["Male" ,"Female", "Unknown/Invalid"])
data1['gender']=le.transform(data1['gender']) 
le = preprocessing.LabelEncoder()
le.fit(['[70-80)', '[30-40)' ,'[50-60)', '[80-90)', '[60-70)' ,'[40-50)' ,'[90-100)',
 '[20-30)', '[10-20)', '[0-10)'])
data1['age']=le.transform(data1['age'])
le = preprocessing.LabelEncoder()
le.fit(['Norm' ,'None', '>8', '>7'])
data1['A1Cresult']=le.transform(data1['A1Cresult'])
le = preprocessing.LabelEncoder()
le.fit(['Yes','No'])
data1['diabetesMed']=le.transform(data1['diabetesMed'])
le = preprocessing.LabelEncoder()
le.fit(['No','Steady','Down','Up'])
data1['insulin']=le.transform(data1['insulin']) 
le = preprocessing.LabelEncoder()
le.fit(['No','Ch'])
data1['change']=le.transform(data1['change']) 


In [7]:
a = data1['diag_3']
count = 0
list1 = list()
for i in a:
    if(i.startswith('V') or i.startswith('E')):
        list1.append(i)
    count = count + 1
for i in list1:
    a = a.replace(i,"?")     
data1['diag_3'] = a



In [8]:
a = data1['diag_1']
count = 0
list1 = list()
for i in a:
    if(i.startswith('V') or i.startswith('E')):
        list1.append(i)
    count = count + 1
for i in list1:
    a = a.replace(i,"?")     
data1['diag_1'] = a




In [9]:
a = data1['diag_2']
count = 0
list1 = list()
for i in a:
    if(i.startswith('V') or i.startswith('E')):
        list1.append(i)
    count = count + 1
for i in list1:
    a = a.replace(i,"?")     
data1['diag_2'] = a


In [10]:
data1['diag_3'].unique()

array(['255', '?', '403', '250', '38', '486', '996', '197', '250.6',
       '427', '627', '414', '416', '582', '250.01', '263', '250.42',
       '276', '482', '401', '250.41', '585', '781', '278', '998', '428',
       '568', '682', '250.02', '305', '707', '496', '599', '424', '518',
       '553', '794', '411', '531', '511', '490', '562', '250.8', '250.7',
       '250.52', '784', '491', '581', '420', '724', '730', '789', '131',
       '250.82', '999', '41', '493', '250.03', '753', '786', '529', '425',
       '595', '303', '560', '711', '8', '492', '332', '296', '438', '362',
       '250.4', '654', '244', '737', '625', '681', '250.51', '404', '810',
       '280', '440', '785', '569', '272', '997', '250.43', '918', '584',
       '54', '788', '426', '722', '250.92', '196', '461', '535', '787',
       '891', '284', '458', '648', '780', '182', '285', '593', '413',
       '664', '564', '201', '356', '292', '782', '715', '473', '455',
       '714', '357', '348', '294', '250.23', '459', '437', 

In [11]:
data1.shape

(62945, 33)

In [12]:
data1 = data1.replace("?",np.nan)
data1 = data1.dropna()
data1.shape

(57574, 33)

In [13]:
data2 = data1

In [14]:
dupes=data2.duplicated()
sum(dupes)

0

<h2> Variance Threshold </h2>

In [15]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(data2)
idxs_selected = sel.get_support(indices=True)
features_dataframe_new = data2.columns[idxs_selected]
print(features_dataframe_new)

Index(['race', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'insulin', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')


In [16]:
data2 = data2[['race', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'insulin', 'change',
       'diabetesMed', 'readmitted']]

In [17]:
data2.shape

(57574, 20)

In [18]:
data2['diag_3'].describe()

count     57574
unique      598
top         250
freq       7242
Name: diag_3, dtype: object

<h1> Normalization </h1>

In [19]:
from sklearn.preprocessing import normalize
array1 = data2.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
result = normalize(X, norm='l2', axis=1, copy=True, return_norm=False)

In [20]:
data2.columns

Index(['race', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'insulin', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')

In [21]:
result = pd.DataFrame(result,columns=['race', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'insulin', 'change',
       'diabetesMed'])
result['readmitted'] = Y
data2 = result

In [22]:
data2.head()

race    gender       age  time_in_hospital  num_lab_procedures  \
0  0.004389  0.000000  0.002195          0.006584            0.129484   
1  0.004193  0.002097  0.006290          0.004193            0.092257   
2  0.005575  0.002788  0.011151          0.002788            0.142172   
3  0.003146  0.001573  0.007865          0.004719            0.048760   
4  0.002847  0.001424  0.009966          0.007118            0.103929   

   num_procedures  num_medications  number_outpatient  number_emergency  \
0        0.000000         0.039504                0.0               0.0   
1        0.002097         0.033548                0.0               0.0   
2        0.000000         0.022302                0.0               0.0   
3        0.009437         0.025166                0.0               0.0   
4        0.000000         0.017084                0.0               0.0   

   number_inpatient    diag_1    diag_2    diag_3  number_diagnoses  \
0               0.0  0.605722  0.548683  0.559635          0.019752   
1               0.0  0.016774  0.525086  0.844986          0.014677   
2               0.0  0.549175  0.437667  0.696922          0.013938   
3               0.0  0.651181  0.646462  0.393225          0.014156   
4               0.0  0.609336  0.700451  0.355920          0.011389   

   A1Cresult  metformin   insulin    change  diabetesMed  readmitted  
0   0.004389   0.002195  0.006584  0.000000     0.002195           1  
1   0.004193   0.002097  0.006290  0.000000     0.002097           0  
2   0.005575   0.002788  0.005575  0.000000     0.002788           0  
3   0.003146   0.001573  0.003146  0.001573     0.001573           1  
4   0.002847   0.001424  0.001424  0.001424     0.001424           1

In [23]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['number_inpatient']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['number_inpatient']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)

(46059, 1) (46059,) (11515, 1) (11515,)


In [24]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5764654798089448
3 0.5860182370820669
5 0.5887103777681285
7 0.5899261832392532
9 0.5927051671732523
11 0.5960920538428137
13 0.597047329570126
15 0.5987841945288754
17 0.5999131567520626
19 0.5990447242726878
21 0.5989578810247503
23 0.6012158054711246
25 0.6010421189752497
27 0.5996526270082501
29 0.5987841945288754
31 0.601476335214937
33 0.6026921406860617
35 0.6029526704298741
37 0.6035605731654364
39 0.6039079461571862
41 0.6023447676943118
43 0.603300043421624
45 0.6040816326530613
47 0.6052105948762484
49 0.6052974381241858


In [25]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5764654798089448
3 0.5810681719496309
5 0.5828050369083804
7 0.5848892748588798
9 0.585670864090317
11 0.5862787668258793
13 0.5867998263135041
15 0.5867129830655666
17 0.5874945722970039
19 0.5878419452887538
21 0.5880156317846288
23 0.5880156317846288
25 0.5883630047763786
27 0.5885366912722536
29 0.5884498480243161
31 0.5889709075119409
33 0.5894051237516283
35 0.5894051237516283
37 0.5897524967433782
39 0.5896656534954408
41 0.5898393399913157
43 0.5900998697351281
45 0.5900130264871907
47 0.5897524967433782
49 0.5897524967433782


In [26]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['race', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'insulin', 'change',
       'diabetesMed']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['race', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'A1Cresult', 'metformin', 'insulin', 'change',
       'diabetesMed']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)

(46059, 19) (46059,) (11515, 19) (11515,)


In [27]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,70,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5306990881458966
3 0.5390360399478941
5 0.5343465045592705
7 0.5347807207989579
9 0.5376465479808945
11 0.5390360399478941
13 0.5328701693443335
15 0.5376465479808945
17 0.534607034303083
19 0.5377333912288319
21 0.5387755102040817
23 0.5397307859313938
25 0.540686061658706
27 0.5387755102040817
29 0.5396439426834564
31 0.5424229266174555
33 0.5452019105514546
35 0.5452887537993921
37 0.5407729049066435
39 0.544159791576205
41 0.5464177160225793
43 0.5465914025184542
45 0.5452019105514546
47 0.5479808944854537
49 0.5455492835432045
51 0.5458098132870169
53 0.5469387755102041
55 0.548936170212766
57 0.5498914459400781
59 0.5481545809813287
61 0.5494572297003908
63 0.5497177594442032
65 0.5496309161962657
67 0.5498046026921407
69 0.5474598349978289


In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=51)
trainx1 = 
knn.fit(trainx, trainy)
predictions = knn.predict(testx)
accuracy = accuracy_score(predictions,testy)
print(i,accuracy)

SyntaxError: invalid syntax (<ipython-input-28-b41b2635d732>, line 4)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5306990881458966
3 0.539209726443769
5 0.5342596613113331
7 0.5372123317412071
9 0.5392965696917065
11 0.540686061658706
13 0.5360833695180199
15 0.5412071211463308
17 0.5377333912288319
19 0.5403386886669561
21 0.5409465914025184
23 0.5412939643942684
25 0.5412071211463308
27 0.5396439426834564
29 0.5396439426834564
31 0.5452887537993921
33 0.5460703430308294
35 0.5479808944854537
37 0.5458098132870169
39 0.5485019539730785
41 0.5498046026921407
43 0.5491966999565784
45 0.5478940512375163
47 0.5475466782457664
49 0.5478940512375163


In [29]:
data3 = data2

<h2> Select K Best </h2>

In [30]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:4,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)

[1.366e-03 1.750e-02 2.113e-03 1.814e-01 1.601e-01 3.975e-01 1.365e-01
 1.544e+00 2.128e+00 7.098e+00 5.261e-01 1.825e-05 1.737e+00 4.371e-01
 3.391e-03 1.857e-02 3.593e-04 9.839e-02 6.305e-02]
[[0.    0.    0.    0.56 ]
 [0.    0.    0.    0.845]
 [0.    0.    0.    0.697]
 [0.    0.    0.    0.393]]
Index(['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3'], dtype='object')


In [31]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)

(46059, 4) (46059,) (11515, 4) (11515,)


In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,100,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5343465045592705
3 0.5455492835432045
5 0.5509335649153279
7 0.5524967433782023
9 0.5567520625271385
11 0.5603994789405123
13 0.5656969170646983
15 0.5686495874945723
17 0.5683890577507599
19 0.5698653929656969
21 0.5670864090316978
23 0.5706469821971342
25 0.5722101606600087
27 0.5755102040816327
29 0.5740338688666956
31 0.5745549283543204
33 0.5742075553625705
35 0.5735996526270083
37 0.5753365175857577
39 0.5732522796352584
41 0.5735996526270083
43 0.5736864958749457
45 0.574294398610508
47 0.5734259661311333
49 0.574468085106383
51 0.5738601823708207
53 0.5768996960486322
55 0.5762917933130699
57 0.576118106817195
59 0.5747286148501954
61 0.5765523230568823
63 0.5785497177594442
65 0.5798523664785062
67 0.5806339557099436
69 0.5793313069908814
71 0.5778549717759445
73 0.5786365610073817
75 0.5778549717759445
77 0.5788970907511941
79 0.5788970907511941
81 0.5793313069908814
83 0.5795049934867564
85 0.5814155449413808
87 0.5806339557099436
89 0.5800260529743813
91 0.5816760746851

In [34]:
train['diag_3'].describe()

count    46059.000000
mean         0.510476
std          0.170130
min          0.004642
25%          0.387585
50%          0.519787
75%          0.628299
max          0.997459
Name: diag_3, dtype: float64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=i)
knn.fit(trainx, trainy)
predictions = knn.predict(testx)
accuracy = accuracy_score(predictions,testy)
print(i,accuracy)

In [46]:
testx1 = pd.DataFrame([], columns = ['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3'])
testx1.loc[1,:] = [0,0,0,0]
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(trainx, trainy)
predicted = knn.predict(testx1)
print("Prediction:",predicted)

Prediction: [1]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

<h2> Select Percentile </h2>

<h3> 1 <h3>

In [76]:
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import chi2
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = SelectPercentile(score_func=chi2, percentile=10)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:4,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)

[1.366e-03 1.750e-02 2.113e-03 1.814e-01 1.601e-01 3.975e-01 1.365e-01
 1.544e+00 2.128e+00 7.098e+00 5.261e-01 1.825e-05 1.737e+00 4.371e-01
 3.391e-03 1.857e-02 3.593e-04 9.839e-02 6.305e-02]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Index(['number_emergency', 'number_inpatient'], dtype='object')


In [121]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['number_emergency', 'number_inpatient']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['number_emergency', 'number_inpatient']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)

(46059, 2) (46059,) (11515, 2) (11515,)


In [122]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,40,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.577768128528007
3 0.584020842379505
5 0.5865392965696917
7 0.5882761615284412
9 0.5882761615284412
11 0.590447242726878
13 0.5934867564046895
15 0.5960920538428137
17 0.5940946591402518
19 0.5927051671732523
21 0.593573599652627
23 0.5939209726443769
25 0.5955709943551889
27 0.596526270082501
29 0.5979157620495007
31 0.5958315240990013
33 0.5973947025618758
35 0.5978289188015632
37 0.5993920972644377
39 0.600173686495875


In [123]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.577768128528007
3 0.5795918367346938
5 0.5819366044290056
7 0.5834997828918802
9 0.58384715588363
11 0.5839339991315675
13 0.58384715588363
15 0.5855840208423795
17 0.5857577073382545
19 0.5867129830655666
21 0.5865392965696917
23 0.5862787668258793
25 0.5872340425531914
27 0.5872340425531914
29 0.5879287885366913
31 0.5882761615284412
33 0.5880156317846288
35 0.5876682587928789
37 0.5875814155449414
39 0.5868866695614416
41 0.587320885801129
43 0.587147199305254
45 0.586973512809379
47 0.587147199305254
49 0.5874077290490665


<h2> 2 </h2>

In [124]:
from sklearn.feature_selection import SelectPercentile
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = SelectPercentile(percentile=20)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:4,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)

[1.588e+00 2.180e+01 2.082e+00 5.599e+01 1.009e+01 1.285e+02 1.986e+01
 2.845e+02 4.907e+02 2.090e+03 9.251e+00 3.390e-04 3.065e+01 3.696e+02
 9.785e+00 5.725e+01 4.591e-01 1.522e+02 1.523e+02]
[[0.    0.    0.    0.02 ]
 [0.    0.    0.    0.015]
 [0.    0.    0.    0.014]
 [0.    0.    0.    0.014]]
Index(['number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses'],
      dtype='object')


In [125]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,100,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

(46059, 4) (46059,) (11515, 4) (11515,)
1 0.5373860182370821
3 0.5478940512375163
5 0.5524099001302649
7 0.5585757707338255
9 0.5679548415110726
11 0.5686495874945723
13 0.5679548415110726
15 0.5746417716022579
17 0.5773339122883195
19 0.580894485453756
21 0.5814155449413808
23 0.5906209292227529
25 0.5913156752062527
27 0.591923577941815
29 0.5908814589665653
31 0.5915762049500651
33 0.5916630481980026
35 0.5931393834129396
37 0.591923577941815
39 0.5908814589665653
41 0.5921841076856275
43 0.5947894051237517
45 0.5963525835866261
47 0.595223621363439
49 0.5960052105948762
51 0.5973078593139384
53 0.5966131133304385
55 0.5940078158923143
57 0.5960920538428137
59 0.5981762917933131
61 0.5980894485453756
63 0.5986105080330004
65 0.5994789405123752
67 0.6003473729917499
69 0.6011289622231871
71 0.6013894919669995
73 0.5996526270082501
75 0.6023447676943118
77 0.6016500217108119
79 0.6022579244463743
81 0.6015631784628745
83 0.603126356925749
85 0.6027789839339991
87 0.6039947894051237
89

In [126]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5373860182370821
3 0.5420755536257056
5 0.5443334780720799
7 0.5496309161962657
9 0.5519756838905775
11 0.5531046461137646
13 0.5531046461137646
15 0.5544941380807642
17 0.5562310030395137
19 0.555188884064264
21 0.5577073382544507
23 0.5602257924446374
25 0.5606600086843248
27 0.561615284411637
29 0.5619626574033869
31 0.562917933130699
33 0.563265306122449
35 0.5639600521059488
37 0.5640468953538862
39 0.5648284845853235
41 0.5638732088580113
43 0.5630916196265741
45 0.5636126791141989
47 0.563438992618324
49 0.5639600521059488


<h3> 3</h3>

In [127]:
from sklearn.feature_selection import SelectPercentile
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = SelectPercentile(percentile=30)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:4,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)

[1.588e+00 2.180e+01 2.082e+00 5.599e+01 1.009e+01 1.285e+02 1.986e+01
 2.845e+02 4.907e+02 2.090e+03 9.251e+00 3.390e-04 3.065e+01 3.696e+02
 9.785e+00 5.725e+01 4.591e-01 1.522e+02 1.523e+02]
[[0.    0.    0.    0.02  0.    0.002]
 [0.    0.    0.    0.015 0.    0.002]
 [0.    0.    0.    0.014 0.    0.003]
 [0.    0.    0.    0.014 0.002 0.002]]
Index(['number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses', 'change', 'diabetesMed'],
      dtype='object')


In [128]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses', 'change', 'diabetesMed']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses', 'change', 'diabetesMed']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,100,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

(46059, 6) (46059,) (11515, 6) (11515,)
1 0.5353017802865827
3 0.5503256621797655
5 0.5584020842379505
7 0.5639600521059488
9 0.5687364307425098
11 0.5735996526270083
13 0.577420755536257
15 0.5768996960486322
17 0.5817629179331307
19 0.5839339991315675
21 0.5848024316109423
23 0.5883630047763786
25 0.5896656534954408
27 0.5877551020408164
29 0.5893182805036908
31 0.5905340859748155
33 0.5909683022145028
35 0.5926183239253148
37 0.5934867564046895
39 0.5931393834129396
41 0.5955709943551889
43 0.5963525835866261
45 0.5973078593139384
47 0.5955709943551889
49 0.5957446808510638
51 0.5943551888840642
53 0.5944420321320018
55 0.5953973078593139
57 0.593573599652627
59 0.5934867564046895
61 0.5940078158923143
63 0.5946157186278767
65 0.5958315240990013
67 0.5963525835866261
69 0.5981762917933131
71 0.5978289188015632
73 0.5973947025618758
75 0.5964394268345636
77 0.5954841511072514
79 0.5972210160660009
81 0.5984368215371255
83 0.6007815892314372
85 0.5984368215371255
87 0.5977420755536257

In [129]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5353017802865827
3 0.5451150673035171
5 0.5506730351715154
7 0.5534520191055146
9 0.5558836300477638
11 0.5574468085106383
13 0.5598784194528875
15 0.560312635692575
17 0.5625705601389492
19 0.5636995223621364
21 0.563438992618324
23 0.564741641337386
25 0.5650021710811984
27 0.5625705601389492
29 0.5630047763786366
31 0.5631784628745115
33 0.5648284845853235
35 0.5645679548415111
37 0.5658706035605732
39 0.5650021710811984
41 0.5655232305688233
43 0.5656100738167608
45 0.5664785062961355
47 0.5652627008250108
49 0.566391663048198


<h3> 4</h3>

In [130]:
from sklearn.feature_selection import SelectPercentile
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = SelectPercentile(score_func=chi2,percentile=30)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:4,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)

[1.366e-03 1.750e-02 2.113e-03 1.814e-01 1.601e-01 3.975e-01 1.365e-01
 1.544e+00 2.128e+00 7.098e+00 5.261e-01 1.825e-05 1.737e+00 4.371e-01
 3.391e-03 1.857e-02 3.593e-04 9.839e-02 6.305e-02]
[[0.    0.    0.    0.606 0.56  0.02 ]
 [0.    0.    0.    0.017 0.845 0.015]
 [0.    0.    0.    0.549 0.697 0.014]
 [0.    0.    0.    0.651 0.393 0.014]]
Index(['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_3', 'number_diagnoses'],
      dtype='object')


In [131]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_3', 'number_diagnoses']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_3', 'number_diagnoses']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,100,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

(46059, 6) (46059,) (11515, 6) (11515,)
1 0.5357359965262701
3 0.5329570125922709
5 0.5336517585757707
7 0.5345201910551455
9 0.5400781589231437
11 0.5408597481545809
13 0.5453755970473295
15 0.5464177160225793
17 0.5429439861050803
19 0.5425966131133304
21 0.5432045158488927
23 0.5443334780720799
25 0.5417281806339557
27 0.5430308293530178
29 0.5429439861050803
31 0.5452887537993921
33 0.5390360399478941
35 0.5388623534520192
37 0.5417281806339557
39 0.5412939643942684
41 0.5385149804602692
43 0.5403386886669561
45 0.5399044724272688
47 0.5399913156752063
49 0.5386018237082066
51 0.540686061658706
53 0.5424229266174555
55 0.5412071211463308
57 0.5403386886669561
59 0.5414676508901433
61 0.5431176726009552
63 0.5389491966999566
65 0.5402518454190187
67 0.5407729049066435
69 0.5415544941380808
71 0.5405992184107685
73 0.5414676508901433
75 0.540686061658706
77 0.5387755102040817
79 0.5387755102040817
81 0.5378202344767694
83 0.5342596613113331
85 0.5345201910551455
87 0.5371254884932697

In [132]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,50,2):
    knn = KNeighborsClassifier(n_neighbors=i,weights="distance")
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

1 0.5357359965262701
3 0.5330438558402084
5 0.5337386018237082
7 0.5357359965262701
9 0.539383412939644
11 0.5427702996092054
13 0.5437255753365176
15 0.5448545375597047
17 0.5424229266174555
19 0.5435518888406426
21 0.5434650455927051
23 0.5455492835432045
25 0.5440729483282675
27 0.5478072079895788
29 0.5445940078158923
31 0.5453755970473295
33 0.5414676508901433
35 0.5437255753365176
37 0.544159791576205
39 0.5443334780720799
41 0.5429439861050803
43 0.5434650455927051
45 0.542509769865393
47 0.5455492835432045
49 0.5460703430308294


<h2> Generic Univariate Approach </h2>

In [93]:
from sklearn.feature_selection import GenericUnivariateSelect
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = GenericUnivariateSelect(mode='fpr')
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[:,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)


[1.588e+00 2.180e+01 2.082e+00 5.599e+01 1.009e+01 1.285e+02 1.986e+01
 2.845e+02 4.907e+02 2.090e+03 9.251e+00 3.390e-04 3.065e+01 3.696e+02
 9.785e+00 5.725e+01 4.591e-01 1.522e+02 1.523e+02]
[[0.    0.007 0.    ... 0.002 0.    0.002]
 [0.002 0.004 0.002 ... 0.002 0.    0.002]
 [0.003 0.003 0.    ... 0.003 0.    0.003]
 ...
 [0.001 0.007 0.002 ... 0.001 0.    0.001]
 [0.    0.004 0.002 ... 0.001 0.001 0.001]
 [0.    0.002 0.003 ... 0.001 0.001 0.001]]
Index(['gender', 'time_in_hospital', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3',
       'number_diagnoses', 'metformin', 'change', 'diabetesMed'],
      dtype='object')


In [95]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['gender', 'time_in_hospital', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3',
       'number_diagnoses', 'metformin', 'change', 'diabetesMed']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['gender', 'time_in_hospital', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_3',
       'number_diagnoses', 'metformin', 'change', 'diabetesMed']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,70,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

(46059, 12) (46059,) (11515, 12) (11515,)
1 0.526704298740773
3 0.5363438992618323
5 0.5352149370386452
7 0.5411202778983935
9 0.5445071645679549
11 0.5494572297003908
13 0.5471993052540165
15 0.5508467216673903
17 0.5536257056013895
19 0.5561441597915762
21 0.5500651324359531
23 0.5512809379070778
25 0.5496309161962657
27 0.5524099001302649
29 0.5518019973947026
31 0.5494572297003908
33 0.5504993486756404
35 0.5517151541467651
37 0.5538862353452019
39 0.5525835866261398
41 0.553365175857577
43 0.552062527138515
45 0.5503256621797655
47 0.5498914459400781
49 0.5513677811550152
51 0.5508467216673903
53 0.5521493703864524
55 0.5526704298740773
57 0.5494572297003908
59 0.5468519322622666
61 0.5513677811550152
63 0.5511940946591403
65 0.5501519756838906
67 0.5506730351715154
69 0.5515414676508902


In [96]:
from sklearn.feature_selection import GenericUnivariateSelect
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = GenericUnivariateSelect(mode='fdr')
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[:,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)

[1.588e+00 2.180e+01 2.082e+00 5.599e+01 1.009e+01 1.285e+02 1.986e+01
 2.845e+02 4.907e+02 2.090e+03 9.251e+00 3.390e-04 3.065e+01 3.696e+02
 9.785e+00 5.725e+01 4.591e-01 1.522e+02 1.523e+02]
[[0.    0.007 0.    ... 0.002 0.    0.002]
 [0.002 0.004 0.002 ... 0.002 0.    0.002]
 [0.003 0.003 0.    ... 0.003 0.    0.003]
 ...
 [0.001 0.007 0.002 ... 0.001 0.    0.001]
 [0.    0.004 0.002 ... 0.001 0.001 0.001]
 [0.    0.002 0.003 ... 0.001 0.001 0.001]]
Index(['gender', 'time_in_hospital', 'num_procedures', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_3', 'number_diagnoses',
       'metformin', 'change', 'diabetesMed'],
      dtype='object')


In [97]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[['gender', 'time_in_hospital', 'num_procedures', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_3', 'number_diagnoses',
       'metformin', 'change', 'diabetesMed']])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[['gender', 'time_in_hospital', 'num_procedures', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_3', 'number_diagnoses',
       'metformin', 'change', 'diabetesMed']])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,70,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

(46059, 11) (46059,) (11515, 11) (11515,)
1 0.5315675206252714
3 0.5398176291793313
5 0.5426834563612679
7 0.5479808944854537
9 0.5539730785931394
11 0.5528441163699522
13 0.5590099869735128
15 0.5566652192792011
17 0.5534520191055146
19 0.555188884064264
21 0.5575336517585757
23 0.5552757273122014
25 0.5587494572297004
27 0.5535388623534521
29 0.5556231003039513
31 0.5551020408163265
33 0.5571862787668259
35 0.5561441597915762
37 0.5609205384281372
39 0.5618758141554494
41 0.5602257924446374
43 0.5598784194528875
45 0.5590099869735128
47 0.5584020842379505
49 0.5583152409900131
51 0.5610942249240122
53 0.562917933130699
55 0.5649153278332609
57 0.5641337386018237
59 0.5636995223621364
61 0.5617021276595745
63 0.5639600521059488
65 0.5656969170646983
67 0.5658706035605732
69 0.5649153278332609


In [101]:
from sklearn.feature_selection import GenericUnivariateSelect
# load data
array1 = data3.values
X = array1[:,0:19]
Y = array1[:,19]
Y = Y.astype('int')
# feature extraction
test = GenericUnivariateSelect(mode='fwe')
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[:,:])
idxs_selected = test.get_support(indices=True)
# Create new dataframe with only desired columns, or overwrite existing
features_dataframe_new = data3.columns[idxs_selected]
print(features_dataframe_new)
from sklearn.model_selection import train_test_split
train,test = train_test_split(data2,test_size=0.2)
trainx = pd.DataFrame(train[features_dataframe_new.values])
trainy = train['readmitted']                           
testx = pd.DataFrame(test[features_dataframe_new.values])
testy = test['readmitted']
print(trainx.shape,trainy.shape,testx.shape,testy.shape)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,70,2):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(trainx, trainy)
    predictions = knn.predict(testx)
    accuracy = accuracy_score(predictions,testy)
    print(i,accuracy)

[1.588e+00 2.180e+01 2.082e+00 5.599e+01 1.009e+01 1.285e+02 1.986e+01
 2.845e+02 4.907e+02 2.090e+03 9.251e+00 3.390e-04 3.065e+01 3.696e+02
 9.785e+00 5.725e+01 4.591e-01 1.522e+02 1.523e+02]
[[0.007 0.    0.    ... 0.002 0.    0.002]
 [0.004 0.002 0.    ... 0.002 0.    0.002]
 [0.003 0.    0.    ... 0.003 0.    0.003]
 ...
 [0.007 0.002 0.002 ... 0.001 0.    0.001]
 [0.004 0.002 0.    ... 0.001 0.001 0.001]
 [0.002 0.003 0.001 ... 0.001 0.001 0.001]]
Index(['time_in_hospital', 'num_procedures', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_3', 'number_diagnoses',
       'metformin', 'change', 'diabetesMed'],
      dtype='object')
(46059, 10) (46059,) (11515, 10) (11515,)
1 0.5278332609639601
3 0.5409465914025184
5 0.5450282240555797
7 0.5544941380807642
9 0.555015197568389
11 0.5594442032132002
13 0.5639600521059488
15 0.5619626574033869
17 0.5665653495440729
19 0.5676074685193226
21 0.5688232739904473
23 0.5683890577507599
25 0.5675206252713851
27 0.5636